/**
 * GET /api/odds
 * Returns normalised sport events with odds lines.
 * In production: ingest from a licensed odds-feed provider and normalise
 * prices with src/lib/odds before returning.
 */
import { NextResponse } from "next/server";
import { SportEvent } from "@/types";
import { americanToDecimal } from "@/lib/odds";

const SAMPLE_EVENTS: SportEvent[] = [
  {
    id: "evt-001",
    sport: "NFL",
    league: "NFL",
    homeTeam: "Kansas City Chiefs",
    awayTeam: "San Francisco 49ers",
    startTime: new Date(Date.now() + 3_600_000).toISOString(),
    status: "SCHEDULED",
    lines: [
      {
        id: "line-001-ml-home",
        eventId: "evt-001",
        marketType: "MONEYLINE",
        label: "Chiefs",
        price: -150,
        normalizedDecimal: americanToDecimal(-150),
        isLive: false,
        updatedAt: new Date().toISOString(),
      },
      {
        id: "line-001-ml-away",
        eventId: "evt-001",
        marketType: "MONEYLINE",
        label: "49ers",
        price: 130,
        normalizedDecimal: americanToDecimal(130),
        isLive: false,
        updatedAt: new Date().toISOString(),
      },
      {
        id: "line-001-spr-home",
        eventId: "evt-001",
        marketType: "SPREAD",
        label: "Chiefs -3.5",
        price: -110,
        normalizedDecimal: americanToDecimal(-110),
        isLive: false,
        updatedAt: new Date().toISOString(),
      },
      {
        id: "line-001-spr-away",
        eventId: "evt-001",
        marketType: "SPREAD",
        label: "49ers +3.5",
        price: -110,
        normalizedDecimal: americanToDecimal(-110),
        isLive: false,
        updatedAt: new Date().toISOString(),
      },
      {
        id: "line-001-tot-over",
        eventId: "evt-001",
        marketType: "TOTAL",
        label: "Over 47.5",
        price: -110,
        normalizedDecimal: americanToDecimal(-110),
        isLive: false,
        updatedAt: new Date().toISOString(),
      },
      {
        id: "line-001-tot-under",
        eventId: "evt-001",
        marketType: "TOTAL",
        label: "Under 47.5",
        price: -110,
        normalizedDecimal: americanToDecimal(-110),
        isLive: false,
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: "evt-002",
    sport: "NBA",
    league: "NBA",
    homeTeam: "Los Angeles Lakers",
    awayTeam: "Boston Celtics",
    startTime: new Date(Date.now() + 7_200_000).toISOString(),
    status: "SCHEDULED",
    lines: [
      {
        id: "line-002-ml-home",
        eventId: "evt-002",
        marketType: "MONEYLINE",
        label: "Lakers",
        price: -120,
        normalizedDecimal: americanToDecimal(-120),
        isLive: false,
        updatedAt: new Date().toISOString(),
      },
      {
        id: "line-002-ml-away",
        eventId: "evt-002",
        marketType: "MONEYLINE",
        label: "Celtics",
        price: 105,
        normalizedDecimal: americanToDecimal(105),
        isLive: false,
        updatedAt: new Date().toISOString(),
      },
      {
        id: "line-002-spr-home",
        eventId: "evt-002",
        marketType: "SPREAD",
        label: "Lakers -2",
        price: -110,
        normalizedDecimal: americanToDecimal(-110),
        isLive: false,
        updatedAt: new Date().toISOString(),
      },
      {
        id: "line-002-spr-away",
        eventId: "evt-002",
        marketType: "SPREAD",
        label: "Celtics +2",
        price: -110,
        normalizedDecimal: americanToDecimal(-110),
        isLive: false,
        updatedAt: new Date().toISOString(),
      },
      {
        id: "line-002-tot-over",
        eventId: "evt-002",
        marketType: "TOTAL",
        label: "Over 225.5",
        price: -110,
        normalizedDecimal: americanToDecimal(-110),
        isLive: false,
        updatedAt: new Date().toISOString(),
      },
      {
        id: "line-002-tot-under",
        eventId: "evt-002",
        marketType: "TOTAL",
        label: "Under 225.5",
        price: -110,
        normalizedDecimal: americanToDecimal(-110),
        isLive: false,
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: "evt-003",
    sport: "NBA",
    league: "NBA",
    homeTeam: "Miami Heat",
    awayTeam: "Golden State Warriors",
    startTime: new Date().toISOString(),
    status: "LIVE",
    lines: [
      {
        id: "line-003-ml-home",
        eventId: "evt-003",
        marketType: "MONEYLINE",
        label: "Heat",
        price: 115,
        normalizedDecimal: americanToDecimal(115),
        isLive: true,
        updatedAt: new Date().toISOString(),
      },
      {
        id: "line-003-ml-away",
        eventId: "evt-003",
        marketType: "MONEYLINE",
        label: "Warriors",
        price: -135,
        normalizedDecimal: americanToDecimal(-135),
        isLive: true,
        updatedAt: new Date().toISOString(),
      },
      {
        id: "line-003-tot-over",
        eventId: "evt-003",
        marketType: "TOTAL",
        label: "Over 218",
        price: -110,
        normalizedDecimal: americanToDecimal(-110),
        isLive: true,
        updatedAt: new Date().toISOString(),
      },
      {
        id: "line-003-tot-under",
        eventId: "evt-003",
        marketType: "TOTAL",
        label: "Under 218",
        price: -110,
        normalizedDecimal: americanToDecimal(-110),
        isLive: true,
        updatedAt: new Date().toISOString(),
      },
    ],
  },
];

export async function GET() {
  return NextResponse.json(SAMPLE_EVENTS);
}
